gui:
  showCommandLog: false
customCommands:
  - key: f
    command: git f
    subprocess: true
    loadingText: applying fixup...
    description: '"git f", fixup previous commit'
    context: files
