gui:
  showCommandLog: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: f
    command: git f
    subprocess: true
    loadingText: applying fixup...
    description: '"git f", fixup previous commit'
    context: files
